version: '3.8'

services:
  webflick:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: webflick
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"